### ISSUE TITLE
Code blocks - dont close correctly

### ISSUE THREAD

**Issue by samedney** [jbroadway/slimdown#1]
Firstly, thank you for this very easy to use library!

Im not sure if Im building my markdown incorrectly, but codeblocks do not seem to close correctly. 

eg. If my code is as follows (first block) it appears as though it was written as beneath (second block):

--

<pre>
This is some text

```
this is some code
```

This is some more text

```
this is some more code
```
</pre>

--

<pre>
This is some text

```
this is some code

This is some more text

this is some more code
```
</pre>

**Comment by lux** [comment]
I believe my fix should take care of this but let me know if you still have issues with it. Cheers!
