### ISSUE TITLE
Deprecated: Use of "self" in callables is deprecated - php 8.2

### ISSUE THREAD

**Issue by stmaccarelli** [jbroadway/slimdown#2]
I got notices of Deprecation.
I fixed this, according to the well written article: https://php.watch/versions/8.2/partially-supported-callable-deprecation

by changing:
```
public static $rules = array (
		'/```(.*?)```/s' => 'self::code_parse',                              // code blocks
		'/\n(#+)(.*)/' => 'self::header',                                   // headers
		'/\!\[([^\[]+)\]\(([^\)]+)\)/' => '<img src=\'\2\' alt=\'\1\' />',  // images
```

to

```
	public static $rules = array (
		'/```(.*?)```/s' => 'code_parse',                              // code blocks
		'/\n(#+)(.*)/' => 'header',     
```

and the render function to

```
public static function render ($text) {
		$text = "\n" . $text . "\n";
		foreach (self::$rules as $regex => $replacement) {
			$callable = self::class .'::'.$replacement;
			if (is_callable ( $callable)) {
				$text = preg_replace_callback ($regex, $callable, $text);
			} else {
				$text = preg_replace ($regex, $replacement, $text);
			}
		}
		return trim ($text);
	}


```

I don't know if this is a fix you can accept, or you want implement another solution.

**Comment by lux** [comment]
I’m on the road and won't be able to test this for a bit. Does your fix work in older versions of PHP as well, or do they need self::class included for that? Whichever way works and maintains backwards compatibility, would you be able to make a PR with the fix? Thanks!

**Comment by stmaccarelli** [comment]
I just tested it with 8.2 and 7.4 and it is working.
I don't know ho far you intend to go for backwards compatibility.

**Comment by lux** [comment]
I think that works for me!

**Comment by lux** [comment]
That works for me!
