### ISSUE TITLE
Bold/italics inside code blocks not handled correctly

### ISSUE THREAD

**Issue by Draco18s** [jbroadway/slimdown#4]
Based on my reading of the regex involved, the bold/italic patterns will detect inside inline (and multiline) code blocks.

Eg:
```text
`private int _some_var = 1; //this should not be replaced`
```

Will get picked up by the italics handling:
![image](https://github.com/jbroadway/slimdown/assets/1750680/d6bf6959-cd15-403e-9297-8255a23a11f9)

Came across this trying to figure out how I could handle this for a Discord bot, as Discord italics are handled with `_` but I want to replace those with `*` due to later text handling systems, but not screw up teletype blocks.

**Comment by Draco18s** [comment]
Found something that'll work for me, and may help actually fix the potential bug. This will match *any* underscore except those inside paired backticks (although if there's an unpaired backtick, the results are kind weird).

```regex
_(?=([^`]*`[^`]*`)*[^`]*$)

**Comment by lux** [comment]
Are you able to make a PR for this?

**Comment by Draco18s** [comment]
> Are you able to make a PR for this?

Not quickly. I'd have to adjust the regex for each of the format types which involves taking what's there, extracting the desired pattern, and wrapping it in:

```regex
(?=([^`]*`[^`]*`)*[^`]*$))(.*?)\1

**Comment by sorenpeter** [comment]
I'm having a similar issue with URLs to images and probably also other links: If there is a underscore in the URL is replaces with `<em>` which breaks the URL.

**Comment by lux** [comment]
Looks like the PR isn't quite ready to merge to fix this. From the test results it looks like it's stripping the contents from the tags like this:

```
<p>And <strong></strong> for something <em></em> different.</p>
```

**Comment by Draco18s** [comment]
> Looks like the PR isn't quite ready to merge to fix this. From the test results it looks like it's stripping the contents from the tags like this:
> 
> ```
> <p>And <strong></strong> for something <em></em> different.</p>
> ```

Thanks for checking that. Will double check the capture group numbers.

**Comment by Draco18s** [comment]
Try the update I just pushed @lux

I had the wrong capture group number in the replacement, should be fixed now, along with some improved handling for links.

**Comment by lux** [comment]
I pushed a couple additional fixes for links and multi-line code blocks and merged the fix. Thanks for getting that working @Draco18s!

**Comment by Draco18s** [comment]
Sure thing! I didn't update any of the test cases for future changes, but a couple off the top of my head:

```text
[A Link _with_ italics](www.test.com/a_b_c.jpg)   ->   <a href="www.test.com/a_b_c.jpg">A Link <em>with</em> italics</a>
[A link with alt text](www.test.com/a_b_c.jpg "Ping!")  ->  <a href="www.test.com/a_b_c.jpg" title="Ping!">A link with alt text</a>
*Italics* <3  ->  <em>Italics</em> <3
```

I have since forgotten what I needed the regex for, but I'm sure it was important.

**Comment by lux** [comment]
Ah yes, I realized images were affected too so I fixed that up as well and added checks to the existing test fixtures to make sure underscores don't mess up URLs in both links and images, along with code blocks.

**Comment by Draco18s** [comment]
👍 Awesome.
